
package Interfaz;


import Controller.controlInserts;
import Controller.datesControl;
import Controller.funciones;
import conexion.ConexionDBOriginal;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class altaAmbulantes extends javax.swing.JFrame {

  ConexionDBOriginal con2 = new ConexionDBOriginal();
   controlInserts contrl = new controlInserts();
   funciones func = new funciones();
    datesControl datCtrl = new datesControl();
    
   List<String> contenGiro = new ArrayList<String>();//lista para guardar el id de cada giro de ambulantes
     List<String> contenResg = new ArrayList<String>();//
     List<String> contenRubGastos = new ArrayList<String>();  
  
     String[][] matTarifs = null, matTarifsResg = null;
     static String idAmbP = "1";
     
    
   
     public altaAmbulantes(String idParam ) {
        initComponents();
        this.idAmbP = idParam;
       
        AutoCompleteDecorator.decorate(jCBoxGirosAmb);
        llenacomboGiros();
        llenaTarifas();
        llenaTarifasResg();
        llenaDats();

        jButton1.setVisible(false);
        jButton4.setVisible(false);
      
           jPaniNIpAYSaMB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfolAmb = new javax.swing.JTextField();
        txtNombAmb = new javax.swing.JTextField();
        txtDirAmb = new javax.swing.JTextField();
        txtObsAmb = new javax.swing.JTextField();
        txtTelAmb = new javax.swing.JTextField();
        jCBoxGirosAmb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCBoxTarifaAmb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBoxResgAmb = new javax.swing.JComboBox<>();
        txtDsctoAmbSem = new javax.swing.JTextField();
        txtCoastInscAmb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCoastSemAmb = new javax.swing.JTextField();
        txtDsctoAmbIns = new javax.swing.JTextField();
        txtDsctoResgAmb = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCoastResgAmb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPaniNIpAYSaMB = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButMantenSubstract = new javax.swing.JButton();
        txtiniSemPaysAmb = new javax.swing.JTextField();
        jLaFechIniPayAmb = new javax.swing.JLabel();
        jButMantenMoore = new javax.swing.JButton();
        txtOcultIniSem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(615, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATOS GENERALES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Folio");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Obs");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Giro");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono");

        txtfolAmb.setEditable(false);
        txtfolAmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtNombAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombAmbKeyReleased(evt);
            }
        });

        txtDirAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDirAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDirAmbKeyReleased(evt);
            }
        });

        txtObsAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtObsAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtObsAmbKeyReleased(evt);
            }
        });

        txtTelAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelAmbKeyReleased(evt);
            }
        });

        jCBoxGirosAmb.setEditable(true);
        jCBoxGirosAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBoxGirosAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBoxGirosAmbKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfolAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDirAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addComponent(txtObsAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addComponent(txtTelAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBoxGirosAmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfolAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObsAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBoxGirosAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TARIFA");

        jCBoxTarifaAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBoxTarifaAmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBoxTarifaAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxTarifaAmbActionPerformed(evt);
            }
        });
        jCBoxTarifaAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBoxTarifaAmbKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Inscripción");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Resguardo");

        jCBoxResgAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBoxResgAmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Ninguno)" }));
        jCBoxResgAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxResgAmbActionPerformed(evt);
            }
        });
        jCBoxResgAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBoxResgAmbKeyReleased(evt);
            }
        });

        txtDsctoAmbSem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDsctoAmbSem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDsctoAmbSemKeyReleased(evt);
            }
        });

        txtCoastInscAmb.setEditable(false);
        txtCoastInscAmb.setBackground(new java.awt.Color(255, 255, 255));
        txtCoastInscAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCoastInscAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoastInscAmbKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Descuento");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Descuento");

        txtCoastSemAmb.setEditable(false);
        txtCoastSemAmb.setBackground(new java.awt.Color(255, 255, 255));
        txtCoastSemAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCoastSemAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoastSemAmbKeyReleased(evt);
            }
        });

        txtDsctoAmbIns.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDsctoAmbIns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDsctoAmbInsKeyReleased(evt);
            }
        });

        txtDsctoResgAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDsctoResgAmb.setText("0");
        txtDsctoResgAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDsctoResgAmbKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Descuento");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("%");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("%");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("%");

        txtCoastResgAmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCoastResgAmb.setText("0");
        txtCoastResgAmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoastResgAmbKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Semana");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBoxTarifaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBoxResgAmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCoastResgAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCoastInscAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCoastSemAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDsctoResgAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDsctoAmbSem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDsctoAmbIns, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBoxTarifaAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoastSemAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoastInscAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCBoxResgAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCoastResgAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDsctoAmbSem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDsctoAmbIns, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDsctoResgAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uicheckOk.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconNewUser.png"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPaniNIpAYSaMB.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("INICIAR PAGOS:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Semana");

        jButMantenSubstract.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButMantenSubstract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        jButMantenSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMantenSubstractActionPerformed(evt);
            }
        });
        jButMantenSubstract.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButMantenSubstractKeyReleased(evt);
            }
        });

        txtiniSemPaysAmb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtiniSemPaysAmb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtiniSemPaysAmb.setText("0");

        jLaFechIniPayAmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLaFechIniPayAmb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLaFechIniPayAmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jButMantenMoore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButMantenMoore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        jButMantenMoore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMantenMooreActionPerformed(evt);
            }
        });
        jButMantenMoore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButMantenMooreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPaniNIpAYSaMBLayout = new javax.swing.GroupLayout(jPaniNIpAYSaMB);
        jPaniNIpAYSaMB.setLayout(jPaniNIpAYSaMBLayout);
        jPaniNIpAYSaMBLayout.setHorizontalGroup(
            jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaniNIpAYSaMBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButMantenSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtiniSemPaysAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLaFechIniPayAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButMantenMoore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOcultIniSem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaniNIpAYSaMBLayout.setVerticalGroup(
            jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaniNIpAYSaMBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaniNIpAYSaMBLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtOcultIniSem))
                    .addGroup(jPaniNIpAYSaMBLayout.createSequentialGroup()
                        .addGroup(jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPaniNIpAYSaMBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButMantenSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLaFechIniPayAmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtiniSemPaysAmb)
                                .addComponent(jButMantenMoore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(12, 12, 12))
                    .addComponent(jPaniNIpAYSaMB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaniNIpAYSaMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBoxTarifaAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxTarifaAmbActionPerformed
        int var = jCBoxTarifaAmb.getSelectedIndex();
        if(var > -1){
            txtCoastSemAmb.setText(matTarifs[var][4]);
            txtCoastInscAmb.setText(matTarifs[var][5]);
        }
    }//GEN-LAST:event_jCBoxTarifaAmbActionPerformed

    private void jCBoxResgAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxResgAmbActionPerformed
         int var = jCBoxResgAmb.getSelectedIndex();
        if(var > -1){
            if(var == 0){
                txtCoastResgAmb.setText("0");
            }else{
                txtCoastResgAmb.setText(matTarifsResg[var - 1][4]);
            }
        }
    }//GEN-LAST:event_jCBoxResgAmbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton1.setVisible(true);
        jButton1.setText("Modificar");
        jButton4.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton1.setVisible(true);
        jButton1.setText("Guardar");
        jButton4.setVisible(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        limpiaCamps();
        jPaniNIpAYSaMB.setVisible(true);
        llenainiSemana();
        txtfolAmb.setText(Integer.toString(func.getUltAmbul() +1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String acct = jButton1.getText();
        List<String> contenData = new ArrayList<String>();
        int indCBGiros = jCBoxGirosAmb.getSelectedIndex(),
              indCBTarifs = jCBoxTarifaAmb.getSelectedIndex(),
              indCBResg = jCBoxResgAmb.getSelectedIndex(),
              semMINUSuno = 0;
        String foli = txtfolAmb.getText(),
              nam = txtNombAmb.getText(),
              dir = txtDirAmb.getText(),
              obs = txtObsAmb.getText(),
              tel = txtTelAmb.getText(),
              descSem = txtDsctoAmbSem.getText(),
              descInsc = txtDsctoAmbIns.getText(),
              descResg = txtDsctoResgAmb.getText(),
              idGir = contenGiro.get(indCBGiros),
              idTar = matTarifs[indCBTarifs][0],
              aPartirPaySem = txtOcultIniSem.getText()
        ;
      
          contenData.add((nam.isEmpty()) ? "" : nam);   
          contenData.add((dir.isEmpty()) ? "" : dir);   
          contenData.add((tel.isEmpty()) ? "" : tel);   
          contenData.add((obs.isEmpty()) ? "" : obs);   
          contenData.add(idGir);   
          contenData.add(idTar);   
          if(indCBResg == 0){
              contenData.add("0");   
          }else{
              contenData.add(matTarifsResg[indCBResg -1][0]);
          }
          contenData.add(descInsc);   
          contenData.add(descSem);   
          contenData.add(descResg);   
          
          if(jPaniNIpAYSaMB.isVisible()){
                semMINUSuno=Integer.parseInt(aPartirPaySem);
                semMINUSuno=semMINUSuno-1;
                contenData.add(Integer.toString(semMINUSuno));
          }
          
          if(!nam.isEmpty() ){
              String queHace = jButton1.getText();
              if(queHace.equals("Guardar"))
                    contrl.guardF5Ambu(0,contenData, foli);
              if(queHace.equals("Modificar"))
                    contrl.guardF5Ambu(1,contenData, foli);
                  
            if(foli.isEmpty())// is new user
                limpiaCamps();
            else//actualiza
                this.dispose();
            
            
  }else{
      JOptionPane.showMessageDialog(null, "Debe ingresar por lo menos Nombre y Obs");
  }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButMantenSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMantenSubstractActionPerformed
        String fin = txtiniSemPaysAmb.getText(),
                idSemOc = txtOcultIniSem.getText(),
                aux = "";
        int idSemMantini = Integer.parseInt(idSemOc);
        String[] arr = null;
        //amountThree.compareTo(func.getSum(amountOne, amountTwo)) >= 0
        idSemMantini--;
        arr = contrl.regSemanas(idSemMantini);
        aux = datCtrl.getWeekStartDate(arr[3]) + " - "+ datCtrl.getWeekStartDate(arr[4]);
        txtOcultIniSem.setText(arr[0]);
        txtiniSemPaysAmb.setText(arr[2]);
        jLaFechIniPayAmb.setText(aux);
    }//GEN-LAST:event_jButMantenSubstractActionPerformed

    private void jButMantenMooreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMantenMooreActionPerformed
        String fin = txtiniSemPaysAmb.getText(),
                idSemOc = txtOcultIniSem.getText(),
                aux = "";
        int idSemMantini = Integer.parseInt(idSemOc);
        String[] arr = null;
        //amountThree.compareTo(func.getSum(amountOne, amountTwo)) >= 0
        idSemMantini++;
        arr = contrl.regSemanas(idSemMantini);
        aux = datCtrl.getWeekStartDate(arr[3]) + " - "+ datCtrl.getWeekStartDate(arr[4]);
        txtOcultIniSem.setText(arr[0]);
        txtiniSemPaysAmb.setText(arr[2]);
        jLaFechIniPayAmb.setText(aux);
    }//GEN-LAST:event_jButMantenMooreActionPerformed

    private void txtNombAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombAmbKeyReleased
     int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtNombAmbKeyReleased

    private void txtDirAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtDirAmbKeyReleased

    private void txtObsAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtObsAmbKeyReleased

    private void jCBoxGirosAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBoxGirosAmbKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxGirosAmbKeyReleased

    private void txtTelAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtTelAmbKeyReleased

    private void jCBoxTarifaAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBoxTarifaAmbKeyReleased
            int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_jCBoxTarifaAmbKeyReleased

    private void txtCoastSemAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoastSemAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtCoastSemAmbKeyReleased

    private void txtDsctoAmbSemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDsctoAmbSemKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtDsctoAmbSemKeyReleased

    private void txtCoastInscAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoastInscAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtCoastInscAmbKeyReleased

    private void txtDsctoAmbInsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDsctoAmbInsKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtDsctoAmbInsKeyReleased

    private void txtCoastResgAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoastResgAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtCoastResgAmbKeyReleased

    private void jCBoxResgAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBoxResgAmbKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_jCBoxResgAmbKeyReleased

    private void txtDsctoResgAmbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDsctoResgAmbKeyReleased
            int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_txtDsctoResgAmbKeyReleased

    private void jButMantenSubstractKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButMantenSubstractKeyReleased
             int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_jButMantenSubstractKeyReleased

    private void jButMantenMooreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButMantenMooreKeyReleased
            int var = evt.getKeyCode();
          if(var == 27 ){
                 this.dispose();
            }else{
            if(var == KeyEvent.VK_ENTER){
                jButton1.doClick();
            }
          }
    }//GEN-LAST:event_jButMantenMooreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaAmbulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaAmbulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaAmbulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaAmbulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaAmbulantes(idAmbP).setVisible(true);
            }
        });
    }
    
    public void llenainiSemana(){
         String[] semA = func.lapsoSemanasIni(datCtrl.setDateActual());
          txtiniSemPaysAmb.setText(semA[2]);
          txtOcultIniSem.setText(semA[0]);
            jLaFechIniPayAmb.setText(datCtrl.getWeekStartDate(semA[3]) +" - "+datCtrl.getWeekStartDate(semA[4]));
    }
    
    public void llenaTarifas(){
        matTarifs = regTarifasToAmb();
        jCBoxTarifaAmb.removeAllItems();
        for (int i = 0; i < matTarifs.length; i++) {
            for (int j = 0; j < matTarifs[0].length; j++) {
                if(j == 2){
                    jCBoxTarifaAmb.addItem(matTarifs[i][j]);
                }
            }
          
        }
    }
            
    //funciones para lllenar campos
    public void llenaTarifasResg(){
        matTarifsResg = regTarifasResgToAmb();
        for (int i = 0; i < matTarifsResg.length; i++) {
            for (int j = 0; j < matTarifsResg[0].length; j++) {
         //      System.out.print("["+matTarifsResg[i][j]+"]");
                if(j == 2){
                    jCBoxResgAmb.addItem(matTarifsResg[i][j]);
                }
            }
           // System.out.println("");
        }
    }
    
    //funciones para lllenar campos de ambulante
    public void llenaDats(){
        String[] dats = func.getAllDataAmb(idAmbP);
        txtfolAmb.setText(dats[0]);
        txtNombAmb.setText(dats[1]);
        txtDirAmb.setText(dats[2]);
        txtObsAmb.setText(dats[4]);
        txtTelAmb.setText(dats[3]);
        jCBoxGirosAmb.setSelectedItem(func.getnombreTarifaAmb("giro","giros",dats[5]));
   //     System.out.println(dats[5]+" "+jCBoxGirosAmb.getSelectedIndex()+" " );
        jCBoxTarifaAmb.setSelectedItem(func.getnombreTarifaAmb("descripcion","tarifas",dats[6]));
        
        if(dats[7].equals("0")){
            jCBoxResgAmb.setSelectedIndex(0);
        }else{
       for (int i = 0; i < matTarifsResg.length; i++) {
            for (int j = 0; j < matTarifsResg[0].length; j++) {
                if(j == 0){
                //    System.err.println(dats[7]+" == "+matTarifsResg[i][j+2]);
                    if(dats[7].equals(matTarifsResg[i][j])){
                        jCBoxResgAmb.setSelectedItem(matTarifsResg[i][j+2]);
                    }
                }
            }
             }
            
//            jCBoxResgAmb.setSelectedIndex(Integer.parseInt(matTarifsResg[Integer.parseInt(dats[7]) -6][0]) -5);
        }//else si tiene algun idResguardo
        txtDsctoAmbSem.setText(dats[9]);
        txtDsctoAmbIns.setText(dats[8]);
        txtDsctoResgAmb.setText(dats[10]);
        
    }
    
    //metodo para llenar combo de ambulantes
     private void llenacomboGiros() {
            Connection cn = con2.conexion();
            contenGiro.clear();
            jCBoxGirosAmb.removeAllItems();
            String consul = "SELECT id, giro from giros ORDER BY id";
            Statement st = null;
            ResultSet rs = null;
            try {
                st = cn.createStatement();
                rs = st.executeQuery(consul);
                while (rs.next()) {
                    contenGiro.add(rs.getString(1));
                    jCBoxGirosAmb.addItem(rs.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(altaAmbulantes.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (st != null) {
                        st.close();
                    }
                    if (cn != null) {
                        cn.close();
                    }
                } catch (SQLException ex) {
                    System.err.println(ex.getMessage());
                }
            }
    }//Llena getAreas 
        
//metodo para llenar combo de tarifas de ambulantes
     public String[][] regTarifasToAmb(){
        Connection cn = con2.conexion();
          String sql ="",aux;
             sql = "SELECT * FROM tarifas WHERE rubro = 1 order by id ";      
             int i =0,cantFilas=0, cont=1,cantColumnas=0;
             String[][] mat=null, mat2=null;
              int[] arrIdPedido = null;//int para usar hashMap
            Statement st = null;
            ResultSet rs = null;            
            try {
                st = cn.createStatement();
                rs = st.executeQuery(sql);
                cantColumnas = rs.getMetaData().getColumnCount();
               if(rs.last()){//Nos posicionamos al final
                    cantFilas = rs.getRow();//sacamos la cantidad de filas/registros
                    rs.beforeFirst();//nos posicionamos antes del inicio (como viene por defecto)
                }
               mat = new String[cantFilas][cantColumnas];
               //aqui iria crear matriz
                while(rs.next())
                {//es necesario el for para llenar dinamicamente la lista, ya que varia el numero de columnas de las tablas
                      for (int x=1;x<= rs.getMetaData().getColumnCount();x++) {
                           // System.out.print("| "+rs.getString(x)+" |");
                             mat[i][x-1]=rs.getString(x);
                      //System.out.print(x+" -> "+rs.getString(x));                   
                      }//for
                       i++;
                }//whilE
            } catch (SQLException ex) {
                Logger.getLogger(altaAmbulantes.class.getName()).log(Level.SEVERE, null, ex);
            }finally{               
//             System.out.println("cierra conexion a la base de datos");    
             try {        
                 if(st != null) st.close();                
                 if(cn !=null) cn.close();
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,ex.getMessage()); 
             }
         }//finally        
           if (cantFilas == 0){
                mat=null;
                mat = new String[1][cantColumnas];
                
                for (int j = 0; j < mat[0].length; j++) {
                     mat[0][j]="NO DATA";
                }
           }
return mat;  
}//@end regTarifasToAmb
        
//metodo para llenar combo de tarifas de ambulantes
     public String[][] regTarifasResgToAmb(){
        Connection cn = con2.conexion();
          String sql ="",aux;
             sql = "SELECT * FROM tarifas WHERE rubro = 3 ";      
             int i =0,cantFilas=0, cont=1,cantColumnas=0;
             String[][] mat=null, mat2=null;
              int[] arrIdPedido = null;//int para usar hashMap
            Statement st = null;
            ResultSet rs = null;            
            try {
                st = cn.createStatement();
                rs = st.executeQuery(sql);
                cantColumnas = rs.getMetaData().getColumnCount();
               if(rs.last()){//Nos posicionamos al final
                    cantFilas = rs.getRow();//sacamos la cantidad de filas/registros
                    rs.beforeFirst();//nos posicionamos antes del inicio (como viene por defecto)
                }
               mat = new String[cantFilas][cantColumnas];
               //aqui iria crear matriz
                while(rs.next())
                {//es necesario el for para llenar dinamicamente la lista, ya que varia el numero de columnas de las tablas
                      for (int x=1;x<= rs.getMetaData().getColumnCount();x++) {
                           // System.out.print("| "+rs.getString(x)+" |");
                             mat[i][x-1]=rs.getString(x);
                      //System.out.print(x+" -> "+rs.getString(x));                   
                      }//for
                       i++;
                }//whilE
            } catch (SQLException ex) {
                Logger.getLogger(altaAmbulantes.class.getName()).log(Level.SEVERE, null, ex);
            }finally{               
//             System.out.println("cierra conexion a la base de datos");    
             try {        
                 if(st != null) st.close();                
                 if(cn !=null) cn.close();
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,ex.getMessage()); 
             }
         }//finally        
           if (cantFilas == 0){
                mat=null;
                mat = new String[1][cantColumnas];
                
                for (int j = 0; j < mat[0].length; j++) {
                     mat[0][j]="NO DATA";
                }
           }
return mat;  
}//@end regTarifasResgToAmb
        
     public void limpiaCamps(){
            txtfolAmb.setText("");
            txtNombAmb.setText("");
            txtDirAmb.setText("");
            txtObsAmb.setText("");
            jCBoxGirosAmb.setSelectedIndex(0);
            txtTelAmb.setText("");
            jCBoxTarifaAmb.setSelectedIndex(0);
            txtDsctoAmbSem.setText("0");
            txtDsctoAmbIns.setText("0");
            txtDsctoResgAmb.setText("0");
            jCBoxResgAmb.setSelectedIndex(0);
        }//@end limpiaCamps

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButMantenMoore;
    private javax.swing.JButton jButMantenSubstract;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCBoxGirosAmb;
    private javax.swing.JComboBox<String> jCBoxResgAmb;
    private javax.swing.JComboBox<String> jCBoxTarifaAmb;
    private javax.swing.JLabel jLaFechIniPayAmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPaniNIpAYSaMB;
    private javax.swing.JTextField txtCoastInscAmb;
    private javax.swing.JTextField txtCoastResgAmb;
    private javax.swing.JTextField txtCoastSemAmb;
    private javax.swing.JTextField txtDirAmb;
    private javax.swing.JTextField txtDsctoAmbIns;
    private javax.swing.JTextField txtDsctoAmbSem;
    private javax.swing.JTextField txtDsctoResgAmb;
    private javax.swing.JTextField txtNombAmb;
    private javax.swing.JTextField txtObsAmb;
    private javax.swing.JTextField txtOcultIniSem;
    private javax.swing.JTextField txtTelAmb;
    private javax.swing.JTextField txtfolAmb;
    private javax.swing.JTextField txtiniSemPaysAmb;
    // End of variables declaration//GEN-END:variables
}
