/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.internos.jpanels;

import Controller.controlInserts;
import Controller.datesControl;
import Controller.funciones;
import conexion.ConexionDBOriginal;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import renderTable.TModel;
import tickets.Jasper.Reportes;


public class reportes extends javax.swing.JPanel {

    datesControl datCtrl = new datesControl();
    ConexionDBOriginal con2 = new ConexionDBOriginal();
    controlInserts contrl = new controlInserts();
    funciones func = new funciones();
    Reportes rP = new Reportes();
    
    String[] cabAreasPays = {"# Ticket", "Hora", "Concepto", "Nombre", "Monto"},
            cabGastCajas = {"#Folio", "Hora", "Concepto", "Importe"};
    
    List<String> idCajeros = new ArrayList<String>();
    String[] semanaAct = null;
    
    String buscarTurn ="0";
    public reportes() {
        initComponents();
        
        llenacombCajeros();//llenamos el combo con nombre de cajeros 
        jCalendar1.setMaxSelectableDate(datCtrl.cargafecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialCalendarMantenim = new javax.swing.JDialog();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton42 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabViewTurnos = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabDetailTurnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCmbBCajeros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabViewFolio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jCmBoxIdCancel = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jDialCalendarMantenim.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialCalendarMantenim.setTitle("Elija semana");
        jDialCalendarMantenim.setResizable(false);
        jDialCalendarMantenim.setSize(new java.awt.Dimension(450, 300));
        jDialCalendarMantenim.setType(java.awt.Window.Type.UTILITY);

        jCalendar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCalendar1.setDecorationBordersVisible(true);
        jCalendar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton42.setText("Seleccionar");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialCalendarMantenimLayout = new javax.swing.GroupLayout(jDialCalendarMantenim.getContentPane());
        jDialCalendarMantenim.getContentPane().setLayout(jDialCalendarMantenimLayout);
        jDialCalendarMantenimLayout.setHorizontalGroup(
            jDialCalendarMantenimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialCalendarMantenimLayout.createSequentialGroup()
                .addGroup(jDialCalendarMantenimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialCalendarMantenimLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialCalendarMantenimLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jDialCalendarMantenimLayout.setVerticalGroup(
            jDialCalendarMantenimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialCalendarMantenimLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setDividerLocation(650);
        jSplitPane1.setResizeWeight(0.5);

        jTabViewTurnos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabViewTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turno", "Cajero", "Inicio", "Finalizado", "Duracion"
            }
        ));
        jTabViewTurnos.setRowHeight(25);
        jTabViewTurnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabViewTurnosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTabViewTurnos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel5);

        jTabDetailTurnos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabDetailTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Ticket", "Hora", "Concepto", "Nombre"
            }
        ));
        jTabDetailTurnos.setRowHeight(25);
        jTabDetailTurnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabDetailTurnosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTabDetailTurnos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cajero(a):");

        jCmbBCajeros.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCmbBCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBCajerosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Turno:");

        jLabViewFolio.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabViewFolio.setText("---");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cobros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Salidas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Re- Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Esta Semana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("Otra semana");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSplitPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbBCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabViewFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jCmbBCajeros, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabViewFolio, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Corte de caja", new javax.swing.ImageIcon(getClass().getResource("/images/caja-registradora.png")), jPanel1); // NOI18N

        jSplitPane2.setDividerLocation(650);
        jSplitPane2.setResizeWeight(0.5);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel7);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel8);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cuenta:");

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setText("Esta Semana");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton11.setText("Otra Semana");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmBoxIdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmBoxIdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancelaciones", new javax.swing.ImageIcon(getClass().getResource("/images/exit.png")), jPanel2); // NOI18N

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#Ticket", "Fecha", "Hora", "Concepto", "Semana", "Nombre"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ingreso");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rubro");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Areas", "Ambulantes", "Cargadores", "Otros Rubros" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresos", new javax.swing.ImageIcon(getClass().getResource("/images/dinero-cobros.png")), jPanel3); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ingreso");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Gastos" }));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Hora", "Rubro", "Concepto", "Cajero"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setText("<html>\nPor fecha <br> de registro\n</html>");

        jButton6.setText("Semana");

        jButton7.setText("Fecha");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton8.setText("Imprimir");

        jButton9.setText("Guardar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addComponent(jLabel7)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Egresos", new javax.swing.ImageIcon(getClass().getResource("/images/nomina.png")), jPanel4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbBCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBCajerosActionPerformed
        int getElig = jCmbBCajeros.getSelectedIndex();
        String idUser = "";
        if(getElig > -1){
            if(getElig == 0){
              //  JOptionPane.showMessageDialog(null, "Cargar todos");
            }    
            if(getElig > 0){
                idUser = idCajeros.get(getElig - 1);
                JOptionPane.showMessageDialog(null, "id es"+idUser);
            }            
        }
    }//GEN-LAST:event_jCmbBCajerosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getIntervalTurns(0,"","","");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        String var = datCtrl.getFechaCal(jCalendar1),
                tittol = jDialCalendarMantenim.getTitle();
        semanaAct = func.getSemanTableAct(var);
        if(tittol.equals("Corte de caja"))
            getIntervalTurns(1,"",semanaAct[3],semanaAct[4]);//opc,idUser,fech1,fech2
        
        if(tittol.equals("Cancelaciones"))
            getIntervalTurns2(1,"",semanaAct[3],semanaAct[4]);//opc,idUser,fech1,fech2

        jDialCalendarMantenim.dispose();
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jDialCalendarMantenim.setLocationRelativeTo(this);
        jDialCalendarMantenim.setVisible(true);
        jDialCalendarMantenim.setEnabled(true);
        jDialCalendarMantenim.setTitle("Corte de caja");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTabViewTurnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabViewTurnosMouseClicked
    //    int numTurn = jTabViewTurnos.getSelectedRow();
        
            if(evt.getClickCount() > 1){
                jButton1.doClick();/*
                    if(numTurn > -1){
                        buscarTurn = jTabViewTurnos.getValueAt(numTurn, 0).toString();
                        String[][] mat = contrl.matrizgetTicketsDia("",buscarTurn);
                        jTabDetailTurnos.setModel(new TModel(mat, cabAreasPays));
                    }*/
            }
    }//GEN-LAST:event_jTabViewTurnosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(buscarTurn.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe elejir un turno");
        }else{
        
        String[] turns = func.getTurnoData(Integer.parseInt(buscarTurn));
        String[] infoUser = func.getnombreUsuario(Integer.parseInt(turns[1]));
        String[] paramDats = new String[7];
        
        paramDats[0] = infoUser[1];
        paramDats[1] = turns[3];
        paramDats[2] = turns[4];
        paramDats[3] = turns[2];
        paramDats[4] = sumCorteCaj(buscarTurn);
        paramDats[5] = func.totalturno(6,buscarTurn);
        
        BigDecimal salInic = new BigDecimal(turns[2]);
        BigDecimal Cobros = new BigDecimal(paramDats[4]);
        BigDecimal gastosCaj = new BigDecimal(paramDats[5]);
        
        paramDats[6] = func.getDifference(func.getSum(Cobros, salInic), gastosCaj).toString();
        
        rP.imprim80MM_corteCaja(buscarTurn,false,paramDats);
        //rP.creListenerButton(Integer.parseInt(infoUser[6]), infoUser[2],infoUser[0]);    
        }        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int numTurn = jTabViewTurnos.getSelectedRow();
                    if(numTurn > -1){
                        buscarTurn = jTabViewTurnos.getValueAt(numTurn, 0).toString();
                        jLabViewFolio.setText(buscarTurn);
                        String[][] mat = contrl.matrizgetTicketsDia("",buscarTurn);
                        jTabDetailTurnos.setModel(new TModel(mat, cabAreasPays));
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe elegir un Turno");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(buscarTurn.equals("0")){
                JOptionPane.showMessageDialog(null, "Debe elejir un turno");
          }else{
                String[][] mat = func.getGastosCajTurn("",buscarTurn);
                jTabDetailTurnos.setModel(new TModel(mat, cabGastCajas));
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabDetailTurnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabDetailTurnosMouseClicked
        if(evt.getClickCount() > 1){ 
        int fila = jTabDetailTurnos.getSelectedRow();
                if(fila >= 0){
                    String mostTic = jTabDetailTurnos.getValueAt(fila, 0).toString(),
                            concepto = jTabDetailTurnos.getValueAt(fila, 2).toString();
                    if(concepto.equals("Pago Areas")){
                        String[] dat = rP.getUltimPagoarea(mostTic);
                        rP.imprim80MM(mostTic, dat,false);
                    }
                    if(concepto.equals("Pago Ambulantes")){
                        String[] dat = rP.getTickPagoAmbu(mostTic);
                        rP.imprim80MMAmbus(mostTic, dat,false);
                    }
                    if(concepto.equals("Pago Cargadores")){                    
                        String[] dat = rP.getTickPagoCargad(mostTic);
                        rP.imprim80MMCargad(mostTic, dat,false);
                    }
                    if(concepto.equals("Pago Infraccion")){                    
                         rP.imprim80MM_Infrac(mostTic,false);
                    }
                    if(concepto.equals("Varios Amb.") || concepto.equals("Varios Cte.") || concepto.equals("Varios Carg.")){                    
                         String[] dat = rP.getTickOthers(mostTic);
                         rP.imprim80MMOthers(mostTic,dat,false);
                    }
                    if(concepto.equals("Pago Renta Carg")){                    
                         rP.imprim80MM_CargRent(mostTic,false);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Debe elegir que mostrar");
                }
        }
    }//GEN-LAST:event_jTabDetailTurnosMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                getIntervalTurns2(0,"","","");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       jDialCalendarMantenim.setLocationRelativeTo(this);
        jDialCalendarMantenim.setVisible(true);
        jDialCalendarMantenim.setEnabled(true);
        jDialCalendarMantenim.setTitle("Cancelaciones");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if(evt.getClickCount() > 1){
        int numTurn = jTable2.getSelectedRow();
                    if(numTurn > -1){
                        buscarTurn = jTable2.getValueAt(numTurn, 0).toString();
                        jLabViewFolio.setText(buscarTurn);
                        String[][] mat = contrl.matrizgetTicketsDiaCancel("",buscarTurn);
                        jTable1.setModel(new TModel(mat, cabAreasPays));
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe elegir un Turno");
                    }
        }
    }//GEN-LAST:event_jTable2MouseClicked

        //funcion para busqueda automatica de otros conceptos
        void getIntervalTurns(int opc, String idUsers,String fech1,String fech2){
                Connection cn = con2.conexion();
                DefaultTableModel modelo = new DefaultTableModel()
                { 
                    @Override
                    public boolean isCellEditable (int fila, int columna) {
                        return false;
                    }
                };
                String consul="";
                if(opc == 0){
                    consul ="SELECT  turnos.id,usuarios.nombre,turnos.finicial,turnos.ffinal\n" +
                            "FROM turnos\n" +
                            "INNER JOIN usuarios\n" +
                            "ON turnos.idusuario = usuarios.id AND turnos.finicial BETWEEN (SELECT semanas.finicial FROM semanas WHERE CURDATE() BETWEEN finicial AND ffinal)\n" +
                            "AND (SELECT semanas.ffinal FROM semanas WHERE CURDATE() BETWEEN finicial AND ffinal)\n" +
                            "ORDER BY turnos.id DESC;";
                }
                if(opc == 1){
                    consul = "SELECT  turnos.id,usuarios.nombre,turnos.finicial,turnos.ffinal\n" +
                        "FROM turnos\n" +
                        "INNER JOIN usuarios\n" +
                        "ON turnos.idusuario = usuarios.id AND turnos.finicial BETWEEN '"+fech1+"' AND '"+fech2+"' \n" +
                        "ORDER BY turnos.id DESC;";
                }
                 //consul = "SELECT id, nombre from ambulantes WHERE id LIKE '"+var+"%'  OR nombre LIKE '"+var+"%' ORDER BY id";
                        modelo.addColumn("#Turno");       
                        modelo.addColumn("Cajero");
                        modelo.addColumn("Inicio");
                        modelo.addColumn("Finalizado");

                jTabViewTurnos.setModel(modelo);
                TableColumnModel columnModel = jTabViewTurnos.getColumnModel();
              jTabViewTurnos.getColumnModel().getColumn(0).setPreferredWidth(80);
                jTabViewTurnos.getColumnModel().getColumn(0).setMaxWidth(150);
                jTabViewTurnos.getColumnModel().getColumn(0).setMinWidth(50);

                 jTabViewTurnos.getColumnModel().getColumn(1).setPreferredWidth(180);
                jTabViewTurnos.getColumnModel().getColumn(1).setMaxWidth(250);
                jTabViewTurnos.getColumnModel().getColumn(1).setMinWidth(180);

                String datos[] =  new String[4];//tenia 4
                Statement st = null;
                ResultSet rs = null;
                try {
                    st = cn.createStatement();
                    rs = st.executeQuery(consul);

                    while(rs.next()){
                        datos[0] =rs.getString(1);
                        datos[1] = rs.getString(2);
                        datos[2] = rs.getString(3);
                        datos[3] = rs.getString(4);
                        modelo.addRow(datos);
                    }
                    jTabViewTurnos.setModel(modelo);
                } catch (SQLException ex) {
                    Logger.getLogger(reportes.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                     try {
                            if(rs != null) rs.close();              
                            if(st != null) st.close();                
                            if(cn !=null) cn.close();
                     } catch (SQLException ex) {
                     }
                 }
    }//@endgetProductsOthers
        
          //funcion para busqueda automatica de otros conceptos
        void getIntervalTurns2(int opc, String idUsers,String fech1,String fech2){
                Connection cn = con2.conexion();
                DefaultTableModel modelo = new DefaultTableModel()
                { 
                    @Override
                    public boolean isCellEditable (int fila, int columna) {
                        return false;
                    }
                };
                String consul="";
                if(opc == 0){
                    consul ="SELECT  turnos.id,usuarios.nombre,turnos.finicial,turnos.ffinal\n" +
                            "FROM turnos\n" +
                            "INNER JOIN usuarios\n" +
                            "ON turnos.idusuario = usuarios.id AND turnos.finicial BETWEEN (SELECT semanas.finicial FROM semanas WHERE CURDATE() BETWEEN finicial AND ffinal)\n" +
                            "AND (SELECT semanas.ffinal FROM semanas WHERE CURDATE() BETWEEN finicial AND ffinal)\n" +
                            "ORDER BY turnos.id DESC;";
                }
                if(opc == 1){
                    consul = "SELECT  turnos.id,usuarios.nombre,turnos.finicial,turnos.ffinal\n" +
                        "FROM turnos\n" +
                        "INNER JOIN usuarios\n" +
                        "ON turnos.idusuario = usuarios.id AND turnos.finicial BETWEEN '"+fech1+"' AND '"+fech2+"' \n" +
                        "ORDER BY turnos.id DESC;";
                }
                 //consul = "SELECT id, nombre from ambulantes WHERE id LIKE '"+var+"%'  OR nombre LIKE '"+var+"%' ORDER BY id";
                        modelo.addColumn("#Turno");       
                        modelo.addColumn("Cajero");
                        modelo.addColumn("Inicio");
                        modelo.addColumn("Finalizado");

                jTable2.setModel(modelo);
                TableColumnModel columnModel = jTable2.getColumnModel();
              jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
                jTable2.getColumnModel().getColumn(0).setMaxWidth(150);
                jTable2.getColumnModel().getColumn(0).setMinWidth(50);

                 jTable2.getColumnModel().getColumn(1).setPreferredWidth(180);
                jTable2.getColumnModel().getColumn(1).setMaxWidth(250);
                jTable2.getColumnModel().getColumn(1).setMinWidth(180);

                String datos[] =  new String[4];//tenia 4
                Statement st = null;
                ResultSet rs = null;
                try {
                    st = cn.createStatement();
                    rs = st.executeQuery(consul);

                    while(rs.next()){
                        datos[0] =rs.getString(1);
                        datos[1] = rs.getString(2);
                        datos[2] = rs.getString(3);
                        datos[3] = rs.getString(4);
                        modelo.addRow(datos);
                    }
                    jTable2.setModel(modelo);
                } catch (SQLException ex) {
                    Logger.getLogger(reportes.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                     try {
                            if(rs != null) rs.close();              
                            if(st != null) st.close();                
                            if(cn !=null) cn.close();
                     } catch (SQLException ex) {
                     }
                 }
    }//@endgetProductsOthers
        
    private void llenacombCajeros(){
            Connection cn = con2.conexion();
            idCajeros.clear();
            jCmbBCajeros.removeAllItems();
            jCmbBCajeros.addItem("Todos");
            
            jCmBoxIdCancel.removeAllItems();
            jCmBoxIdCancel.addItem("Todos"); 
            
            String consul = "SELECT id, nombre from usuarios WHERE id > 0 ORDER BY nombre";
            Statement st = null;
            ResultSet rs = null;
            try {
                st = cn.createStatement();
                rs = st.executeQuery(consul);
                while (rs.next()) {
                    idCajeros.add(rs.getString(1));
                    jCmbBCajeros.addItem(rs.getString(2));
                    jCmBoxIdCancel.addItem(rs.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(reportes.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (st != null) {
                        st.close();
                    }
                    if (cn != null) {
                        cn.close();
                    }
                } catch (SQLException ex) {
                    System.err.println(ex.getMessage());
                }
            }
    }
    
 
    
private String sumCorteCaj(String idTurnon){
              String most = "";
              BigDecimal totAreas = new BigDecimal(func.totalturno(0, idTurnon));
              BigDecimal totAmbus = new BigDecimal(func.totalturno(1, idTurnon));
              BigDecimal totCarg= new BigDecimal(func.totalturno(2, idTurnon));
              BigDecimal totCargRent = new BigDecimal(func.totalturno(3, idTurnon));
              BigDecimal totInfrc = new BigDecimal(func.totalturno(4, idTurnon));
              BigDecimal totOthsVenta = new BigDecimal(func.totalturno(5, idTurnon));
return most = func.getSum(totAreas, func.getSum(totAmbus, func.getSum(totCarg, func.getSum(totCargRent, func.getSum(totInfrc, totOthsVenta))))).toString();
          }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jCmBoxIdCancel;
    private javax.swing.JComboBox<String> jCmbBCajeros;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JDialog jDialCalendarMantenim;
    private javax.swing.JLabel jLabViewFolio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTabDetailTurnos;
    private javax.swing.JTable jTabViewTurnos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
